### ISSUE TITLE
Create and Promote User script fails - Provider missing?

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/aqua-PKC#141]
The script create_and_promote_user.sh is important for us for test deployments and administration of related test accounts.
Currently the script does not function. 

The underlaying functionality is https://www.mediawiki.org/wiki/Manual:CreateAndPromote.php which fails if run with:

 sudo docker exec micro-pkc-mediawiki php maintenance/createAndPromote.php testuser mypassword --sysop
my_wiki: Creating and promoting User:testuser into sysop...

[fc613ae78c76492234795ddd] [no req]   **PasswordError:** The authentication data change was not handled. Maybe no provider was configured?
Backtrace:
from /var/www/html/maintenance/createAndPromote.php(140)
#0 /var/www/html/maintenance/includes/MaintenanceRunner.php(309): CreateAndPromote->execute()
#1 /var/www/html/maintenance/doMaintenance.php(85): MediaWiki\Maintenance\MaintenanceRunner->run()
#2 /var/www/html/maintenance/createAndPromote.php(166): require_once(string)
#3 {main}

**Comment by it-spiderman** [comment]
You cannot use this script with OIDC setups. You can temporarely disable OIDC, run the script and re-enable. But even if it works, how will you login with this user later?

**Comment by FantasticoFox** [comment]
Using the public key as username.

**Comment by FantasticoFox** [comment]
This was replaced with the following script which needs to be run within the mediawiki container:

In docker container run:
php extensions/DataAccounting/maintenance/createSysopUser.php \<username\>
